name: hifzh_master
description: Aplikasi gamifikasi hafalan Al-Qur'an berbasis Flutter

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path_provider: ^2.1.3

  audioplayers: ^6.0.0

  # speech_to_text sudah ada di projectmu
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  permission_handler: ^11.3.0

  # ----- Tambahan untuk Step 8 (rekam + upload) -----
  record: ^4.3.0         # untuk merekam audio dan menyimpan ke file
  http: ^0.13.6          # upload multipart sederhana
  dio: ^5.2.0            # alternatif untuk upload yang lebih lengkap (opsional)
  scrollable_positioned_list: ^0.3.8
  intl: ^0.20.2
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/data/
    - assets/fonts/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri-BoldItalic.ttf
          weight: 700
          style: italic

    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran.ttf
        - asset: assets/fonts/AmiriQuranColored.ttf
